#!/usr/bin/env python3
"""Compute the areas generated by a voronoi diagramation
"""

import argparse
import logging
import time
import os
from os.path import join as pjoin
from logging import debug, info

import numpy as np

def main():
    t0 = time.time()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--outdir', default='/tmp/', help='Output directory')
    args = parser.parse_args()

    logging.basicConfig(format='[%(asctime)s] %(message)s',
    datefmt='%Y%m%d %H:%M', level=logging.INFO)

    if not os.path.isdir(args.outdir): os.mkdir(args.outdir)
    print('For Aiur!')

    info('Elapsed time:{}'.format(time.time()-t0))
if __name__ == "__main__":
    main()

